name: Test PHP simple

on: push

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bonjour !"

  test-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: VÃ©rifier la version PHP
        run: php -v

      - name: Lancer index.php (CLI)
        run: php index.php
